# Generated by Django 6.0.4 on 2026-04-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
